"use client";

import React, { useState } from "react";
import { 
  ArrowRight, 
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export function FAQ() {
    return (
    <section>
        <section id="faq" className="py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto mb-16 max-w-3xl text-center">
            <h2 className="mb-4 text-3xl font-bold sm:text-4xl">
              Frequently Asked Questions
            </h2>
            <p className="text-xl text-muted-foreground">
              Everything you need to know about ArticleAI
            </p>
          </div>
          
          <div className="mx-auto max-w-3xl">
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger>How does ArticleAI generate content?</AccordionTrigger>
                <AccordionContent>
                  ArticleAI uses advanced natural language processing and machine learning algorithms to generate high-quality, original content. Our AI has been trained on millions of articles and can understand context, tone, and style to create content that reads as if it was written by a human expert.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger>Is the content generated by ArticleAI original?</AccordionTrigger>
                <AccordionContent>
                  Yes, all content generated by ArticleAI is original and plagiarism-free. Our AI creates unique content based on your input, not by copying existing content. We also have built-in plagiarism detection to ensure the originality of all generated content.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger>How does ArticleAI optimize content for SEO?</AccordionTrigger>
                <AccordionContent>
                  ArticleAI analyzes top-ranking content for your target keywords and incorporates SEO best practices into the generated content. This includes optimal keyword density, semantic keywords, proper heading structure, readability optimization, and more to help your content rank higher in search results.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-4">
                <AccordionTrigger>Can I edit the content after it's generated?</AccordionTrigger>
                <AccordionContent>
                  Absolutely! After ArticleAI generates content, you have full control to edit, refine, and customize it to match your specific needs. Our built-in editor makes it easy to make changes, and our AI can even suggest improvements as you edit.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-5">
                <AccordionTrigger>What platforms can I publish to directly?</AccordionTrigger>
                <AccordionContent>
                  ArticleAI supports direct publishing to WordPress, Medium, Substack, Ghost, and several other popular content platforms. You can also export your content in various formats including HTML, Markdown, PDF, and Word documents.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-6">
                <AccordionTrigger>Is there a limit to how much content I can generate?</AccordionTrigger>
                <AccordionContent>
                  The content generation limits depend on your subscription plan. The Free plan includes 5 articles per month, the Professional plan includes 50 articles per month, and the Enterprise plan offers unlimited content generation. Each article can be up to 2,000 words in length.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-primary py-24 text-primary-foreground">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="mb-6 text-3xl font-bold sm:text-4xl">
              Ready to Transform Your Content Strategy?
            </h2>
            <p className="mb-8 text-xl opacity-90">
              Join thousands of content creators and marketers who are already using ArticleAI to create high-quality, SEO-optimized content at scale.
            </p>
            <Button size="lg" variant="secondary" className="gap-2">
              Get Started for Free <ArrowRight size={16} />
            </Button>
            <p className="mt-4 text-sm opacity-80">
              No credit card required. 7-day free trial.
            </p>
          </div>
        </div>
      </section>
    </section>
    );
}
