'use client'
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import Markdown from 'markdown-to-jsx'
import { supabase } from "@/lib/supabase/client";
import { useParams } from "next/navigation";
import Link from "next/link";
import { BRAND_NAME } from "@/constant/app.const";
import { useAuth } from "@/hooks/use-auth";


async function fetchBlogPost(id: string) {
  const { data, error } = await supabase.from("Blogs").select("*").eq("id", id).single();
  if (error || !data) {
    throw new Error("Blog post not found.");
  }
  return data;
}


export default function BlogPost() {
  const param = useParams();
  interface BlogPost {
    id: string;
    title: string;
    content: string;
    markdown: string;
    // Add other fields as necessary
  }

  const [blogPost, setBlogPost] = useState<BlogPost | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if(param?.id){
      fetchBlogPost(param.id as string)
        .then(setBlogPost)
        .catch((err) => setError(err.message));
    }
  }, [param.id]);



  if (error) {
    return <div className="text-red-500 pt-16 flex items-center justify-center h-full">{error}</div>;
  }

  if (!blogPost) {
    return <div className="text-gray-500 pt-16 flex items-center justify-center h-full">Loading...</div>;
  }

  return (
    <div className="mt-24 flex items-center flex-wrap flex-col">
      <Markdown className="blog w-[90%]" style={{maxWidth: "1024px"}}>{blogPost.markdown}</Markdown>
      <div className="mt-10 w-full p-4 border-t border-gray-300 text-center text-sm text-gray-600">
        <p>
          This blog was generated by <Link href="/" className="text-primary" >{BRAND_NAME}</Link>.
        </p>
        <Button><Link href="/login">Generate your blog</Link></Button>
      </div>
    </div>
  );
}
